#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Build data/french-conjugations.js — a full French conjugation dataset.

The dataset is generated by a real rule engine driven by open data, never by
hand-written paradigm tables:

  * Verbiste 0.1.49 (GPL-2+, Pierre Sarrazin) — data/conjugation-fr.xml holds the
    148 Bescherelle-style model paradigms, data/verbs-fr.xml maps 7,016 French
    infinitives onto a model.  This drives every SIMPLE tense.
  * Lexique 3.83 (CC BY-SA 4.0, New Lexicon Project / lexique.org) — lemma
    frequencies (freqlemfilms2 = subtitle corpus, freqlemlivres = book corpus)
    give the genuine corpus rank of every verb.
  * English Wiktionary via Wiktextract / kaikki.org (CC BY-SA 4.0 + GFDL) —
    English glosses, the auxiliary (avoir / être / both) each verb takes in the
    compound tenses, and an independent set of inflected forms used for
    cross-validation.
  * ECDICT 1.0.28 (skywind3000, free for any use) — English → Chinese pivot for
    the Chinese gloss.

Compound tenses are built here (Verbiste only stores simple tenses): auxiliary
conjugation + past participle, with être-subject agreement and pronominal
(reflexive) support.

Elision of the SUBJECT pronoun is deliberately NOT baked in: "ai" is stored under
the `je` key, and the app's conjugation engine renders "j'ai".  The `aspirateH`
flag (from Verbiste) tells that layer when elision must be suppressed (je hais,
not j'hais).  Reflexive-pronoun elision ("m'appelle") IS part of the form itself
and is stored.

Usage:
    python3 scripts/build_french_conjugations.py [--work /tmp/frconj] [--limit 1800]

Downloads expected in --work (see DOWNLOADS below for the exact URLs):
    verbiste-0.1.49/data/{conjugation-fr.xml,verbs-fr.xml}
    Lexique383.tsv
    fr-verbs.jsonl        (kaikki.org French by-pos-verb dump)
    stardict.db           (ECDICT sqlite)
"""

import argparse
import json
import os
import re
import sqlite3
import sys
import unicodedata
import xml.etree.ElementTree as ET
from collections import Counter, OrderedDict

DOWNLOADS = """
  http://deb.debian.org/debian/pool/main/v/verbiste/verbiste_0.1.49.orig.tar.gz
  http://www.lexique.org/databases/Lexique383/Lexique383.tsv
  https://kaikki.org/dictionary/French/pos-verb/kaikki.org-dictionary-French-by-pos-verb.jsonl
  https://github.com/skywind3000/ECDICT/releases/download/1.0.28/ecdict-sqlite-28.zip
"""

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_PATH = os.path.join(REPO, 'data', 'french-conjugations.js')

PERSONS = ['je', 'tu', 'il_elle_on', 'nous', 'vous', 'ils_elles']

# The 20 tense/mood groups every non-defective verb must carry.
CANONICAL_TENSES = [
    'indicatif_present', 'indicatif_imparfait', 'indicatif_passe_simple',
    'indicatif_futur_simple', 'indicatif_passe_compose',
    'indicatif_plus_que_parfait', 'indicatif_passe_anterieur',
    'indicatif_futur_anterieur', 'conditionnel_present', 'conditionnel_passe',
    'subjonctif_present', 'subjonctif_imparfait', 'subjonctif_passe',
    'subjonctif_plus_que_parfait', 'imperatif_present', 'imperatif_passe',
    'participe_present', 'participe_passe', 'infinitif_present',
    'infinitif_passe',
]

REFLEXIVE_PRONOUN = {
    'je': 'me', 'tu': 'te', 'il_elle_on': 'se',
    'nous': 'nous', 'vous': 'vous', 'ils_elles': 'se',
}
VOWEL_START = re.compile(r'^[aàâeéèêëiîïoôuùûüyh]', re.IGNORECASE)

SOURCE_LABEL = 'Verbiste 0.1.49 (GPL-2+) + Lexique 3.83 (CC BY-SA 4.0) + Wiktionary/Wiktextract (CC BY-SA 4.0) + ECDICT (EN→ZH pivot)'

# --------------------------------------------------------------------------
# Curated linguistic tables (small, closed classes — each one is verified in
# scripts/validate_french_conjugations.js against the gold set).
# --------------------------------------------------------------------------

# Verbs whose compound tenses take être even though Wiktionary marks them "ae"
# (avoir when transitive, être when intransitive).  These are the textbook
# DR MRS VANDERTRAMP movement verbs; the intransitive/être reading is the one
# taught first, so it is the one drilled.  `auxiliaryAlt` records the other.
ETRE_PREFERRED_FOR_DUAL = {
    'monter', 'remonter', 'descendre', 'redescendre', 'sortir', 'ressortir',
    'passer', 'repasser', 'rentrer', 'retourner', 'entrer', 'tomber', 'retomber',
    'partir', 'repartir', 'demeurer', 'apparaître', 'apparaitre', 'accourir',
    'monter', 'échoir', 'éclore', 'ressusciter', 'redevenir',
}

# Essentially- or commonly-pronominal verbs.  Each is conjugated from its base
# verb's paradigm with the reflexive pronoun and the être auxiliary.
PRONOMINAL_VERBS = [
    # (surface infinitive, base verb, english, chinese)
    ("s'appeler", 'appeler', 'to be called, to be named', '名叫；叫作'),
    ('se lever', 'lever', 'to get up, to stand up', '起床；起身'),
    ('se trouver', 'trouver', 'to be located, to find oneself', '位于；处于'),
    ('se rendre', 'rendre', 'to go to, to surrender', '前往；投降'),
    ('se mettre', 'mettre', 'to start, to place oneself', '开始；置身于'),
    ('se sentir', 'sentir', 'to feel', '感觉；觉得'),
    ('se souvenir', 'souvenir', 'to remember', '记得；回忆起'),
    ('se rappeler', 'rappeler', 'to recall, to remember', '想起；记得'),
    ('se demander', 'demander', 'to wonder', '自问；想知道'),
    ('se passer', 'passer', 'to happen, to take place', '发生；进行'),
    ('se produire', 'produire', 'to occur, to happen', '发生；出现'),
    ('se tourner', 'tourner', 'to turn (oneself)', '转身；转向'),
    ('se lancer', 'lancer', 'to launch oneself, to embark on', '投身；开始'),
    ('se coucher', 'coucher', 'to go to bed, to lie down', '睡觉；躺下'),
    ('se réveiller', 'réveiller', 'to wake up', '醒来；睡醒'),
    ("s'habiller", 'habiller', 'to get dressed', '穿衣服'),
    ('se laver', 'laver', 'to wash oneself', '洗澡；洗漱'),
    ('se dépêcher', 'dépêcher', 'to hurry up', '赶快；匆忙'),
    ('se promener', 'promener', 'to go for a walk', '散步；遛弯'),
    ('se reposer', 'reposer', 'to rest', '休息'),
    ('se tromper', 'tromper', 'to be mistaken', '弄错；搞错'),
    ('se marier', 'marier', 'to get married', '结婚'),
    ('se préparer', 'préparer', 'to get ready', '准备；做准备'),
    ("s'arrêter", 'arrêter', 'to stop (oneself)', '停下；停止'),
    ("s'approcher", 'approcher', 'to come closer', '靠近；走近'),
    ("s'occuper", 'occuper', 'to take care of, to deal with', '照料；负责'),
    ("s'intéresser", 'intéresser', 'to be interested in', '对…感兴趣'),
    ("s'inquiéter", 'inquiéter', 'to worry', '担心；着急'),
    ("s'ennuyer", 'ennuyer', 'to be bored', '感到无聊'),
    ("s'endormir", 'endormir', 'to fall asleep', '入睡；睡着'),
    ("s'installer", 'installer', 'to settle in, to move in', '安顿；住下'),
    ("s'exprimer", 'exprimer', 'to express oneself', '表达自己'),
    ("s'engager", 'engager', 'to commit oneself', '承诺；投身'),
    ("s'adresser", 'adresser', 'to address oneself to, to speak to', '向…讲话；找…'),
    ("s'excuser", 'excuser', 'to apologise', '道歉；抱歉'),
    ("s'asseoir", 'asseoir', 'to sit down', '坐下'),
    ('se taire', 'taire', 'to be quiet, to keep silent', '沉默；不作声'),
    ('se battre', 'battre', 'to fight', '打架；战斗'),
    ('se plaindre', 'plaindre', 'to complain', '抱怨；诉苦'),
    ('se moquer', 'moquer', 'to make fun of', '嘲笑；取笑'),
    ('se servir', 'servir', 'to use, to help oneself', '使用；自取'),
    ('se débrouiller', 'débrouiller', 'to manage, to cope', '设法应付；自己想办法'),
    ('se fâcher', 'fâcher', 'to get angry', '生气；发火'),
    ('se méfier', 'méfier', 'to be wary of, to distrust', '提防；不信任'),
    ("s'enfuir", 'enfuir', 'to flee, to run away', '逃走；逃跑'),
    ("s'évanouir", 'évanouir', 'to faint', '晕倒；昏厥'),
    # Essentially pronominal: the French Wiktionary conjugation table for the
    # bare lemma itself bakes in the reflexive pronoun ("je m'efforce"), i.e.
    # the source treats the verb as existing only in the pronominal voice.
    ("s'efforcer", 'efforcer', 'to strive, to endeavour, to try hard', '努力；尽力'),
    ("s'envoler", 'envoler', 'to fly away, to take off', '起飞；飞走'),
    ("s'emparer", 'emparer', 'to seize, to take hold of', '夺取；抓住'),
    ("s'écrier", 'écrier', 'to cry out, to exclaim', '喊叫；惊呼'),
    ("s'évader", 'évader', 'to escape, to break out', '逃脱；越狱'),
    ("s'acharner", 'acharner', 'to persist relentlessly, to hound', '拼命；执着；穷追不舍'),
    ("s'obstiner", 'obstiner', 'to persist stubbornly', '固执；坚持不改'),
    ("s'épanouir", 'épanouir', 'to blossom, to flourish', '开花；绽放；充分发展'),
    ("s'abstenir", 'abstenir', 'to abstain, to refrain', '戒除；弃权；避免'),
    ("s'absenter", 'absenter', 'to be away, to absent oneself', '离开；缺席'),
    ("s'enquérir", 'enquérir', 'to inquire, to ask about', '打听；询问'),
    ("s'esclaffer", 'esclaffer', 'to burst out laughing', '哈哈大笑'),
    ("s'extasier", 'extasier', 'to be enraptured, to go into raptures over', '赞叹不已；心醉神迷'),
]

# Verbs that exist only (or all but only) in the pronominal voice.  Shipping a
# bare "j'efforce" card would be teaching French that nobody writes, so the
# frequency pass skips these lemmas and they appear solely as the pronominal
# entry above -- with the same corpus rank, since Lexique lemmatises the
# pronominal occurrences onto the bare infinitive.  The first block is
# evidence-driven (Wiktionary's own table for the lemma is pronominal); the
# second block is verbs whose pronominal entry already exists and whose bare
# form is not standard French.
PRONOMINAL_ONLY = {
    'efforcer', 'envoler', 'emparer', 'écrier', 'évanouir', 'évader', 'acharner',
    'obstiner', 'épanouir', 'abstenir', 'absenter', 'enquérir', 'esclaffer',
    'extasier', 'enfuir', 'méfier', 'souvenir',
}

# Hand-checked Chinese glosses for the highest-frequency verbs, where a machine
# pivot through English is most likely to pick a secondary sense.
MANUAL_CHINESE = {
    'être': '是；存在', 'avoir': '有；拥有', 'faire': '做；制作', 'aller': '去；前往',
    'dire': '说；告诉', 'pouvoir': '能够；可以', 'vouloir': '想要；愿意', 'voir': '看见；看到',
    'savoir': '知道；会', 'devoir': '应该；必须', 'venir': '来；来到', 'prendre': '拿；乘坐',
    'parler': '说话；谈论', 'suivre': '跟随；听从', 'falloir': '必须；需要', 'passer': '经过；度过',
    'croire': '相信；认为', 'aimer': '喜欢；爱', 'penser': '思考；认为', 'trouver': '找到；觉得',
    'regarder': '看；注视', 'laisser': '留下；让', 'donner': '给；给予', 'mettre': '放；穿上',
    'attendre': '等待', 'connaître': '认识；了解', 'arriver': '到达；发生', 'rester': '留下；停留',
    'demander': '询问；请求', 'partir': '离开；出发', 'entendre': '听见；听说', 'appeler': '叫；打电话',
    'comprendre': '理解；懂', 'travailler': '工作；学习', 'sortir': '出去；出来', 'tenir': '拿着；坚持',
    'chercher': '寻找；找', 'rendre': '归还；使变得', 'perdre': '失去；输', 'porter': '携带；穿',
    'montrer': '展示；指出', 'commencer': '开始', 'finir': '结束；完成', 'jouer': '玩；演奏',
    'lire': '阅读；读', 'écrire': '写；书写', 'vivre': '生活；活着', 'mourir': '死亡；去世',
    'naître': '出生；诞生', 'boire': '喝；饮', 'manger': '吃', 'dormir': '睡觉',
    'courir': '跑；奔跑', 'ouvrir': '打开；开启', 'offrir': '赠送；提供', 'recevoir': '收到；接待',
    'répondre': '回答；答复', 'entrer': '进入；进去', 'monter': '上升；登上', 'descendre': '下来；下降',
    'tomber': '掉落；跌倒', 'revenir': '回来；返回', 'devenir': '变成；成为', 'choisir': '选择',
    'payer': '支付；付款', 'acheter': '购买；买', 'vendre': '出售；卖', 'apprendre': '学习；得知',
    'oublier': '忘记', 'changer': '改变；更换', 'garder': '保存；看管', 'quitter': '离开；辞去',
    'marcher': '走路；运转', 'arrêter': '停止；逮捕', 'tuer': '杀死', 'jeter': '扔；抛',
    'servir': '服务；充当', 'valoir': '值；等于', 'plaire': '使高兴；讨人喜欢', 'suffire': '足够；满足',
    'conduire': '驾驶；引导', 'construire': '建造；构建', 'produire': '生产；产生', 'traduire': '翻译',
    'craindre': '害怕；担心', 'peindre': '画；涂', 'joindre': '连接；联系', 'résoudre': '解决；决心',
    'vaincre': '战胜；克服', 'coudre': '缝；缝合', 'moudre': '磨；碾', 'acquérir': '获得；取得',
    'cueillir': '采摘；采集', 'fuir': '逃跑；躲避', 'haïr': '憎恨；讨厌', 'rire': '笑',
    'battre': '打；击败', 'pleuvoir': '下雨', 'asseoir': '使坐下；安置', 'nettoyer': '打扫；清洁',
    'essayer': '尝试；试穿', 'envoyer': '发送；派遣', 'préférer': '更喜欢；偏爱', 'espérer': '希望；期望',
    'répéter': '重复；再说', 'emmener': '带走；带去', 'amener': '带来；引起', 'lever': '举起；抬起',
    'peser': '称重；有…重', 'semer': '播种；散布', 'céder': '让步；让出', 'régler': '调节；结算',
}

# Verbs whose Wiktionary entry carries no usable gloss (the page is only a
# form-of/etymology stub).  Most are rare Bescherelle model verbs that the
# paradigm-coverage pass needs.  Hand-written here rather than left empty --
# the alternative is shipping the verb with no meaning, which we never do.
MANUAL_ENGLISH = {
    'médire': 'to speak ill of, to malign',
    'quérir': 'to fetch, to go and get (literary)',
    'gésir': 'to lie, to be lying down',
    'ouïr': 'to hear (archaic)',
    'trôner': 'to sit enthroned, to hold pride of place',
    'écoeurer': 'to sicken, to disgust',
    'férir': 'to strike (only in "sans coup férir")',
    'occire': 'to slay, to kill (archaic)',
    'ester': 'to appear in court, to litigate',
    'brumasser': 'to drizzle, to be misty',
    'ravoir': 'to get back, to have again',
    'sourdre': 'to well up, to spring forth',
    'saouler': 'to make drunk, to intoxicate',
    'soûler': 'to make drunk, to intoxicate',
    'manoeuvrer': 'to manoeuvre, to operate',
    'infiltrer': 'to infiltrate, to seep into',
    'river': 'to rivet, to clinch',
    'chaloir': 'to matter (only in "peu me chaut")',
    'seoir': 'to suit, to become (someone)',
    'échoir': 'to fall due, to devolve upon',
    'déchoir': 'to fall from grace, to decline',
    'oindre': 'to anoint',
    'amuïr': 'to fall silent, to become mute (of a sound)',
    'chauvir': 'to prick up the ears (of a horse or donkey)',
    'apparoir': 'to be evident (legal, in "il appert")',
    'forclore': 'to bar, to foreclose (legal)',
    'occlure': 'to occlude, to close off',
    'receper': 'to coppice, to cut back to the stump',
    'recéper': 'to coppice, to cut back to the stump',
}

MANUAL_ENGLISH_ZH = {
    'médire': '诽谤；说坏话', 'quérir': '寻找；去取', 'gésir': '躺；卧', 'ouïr': '听见',
    'trôner': '高踞；居首位', 'écoeurer': '使恶心；使反感', 'férir': '打击', 'occire': '杀死',
    'ester': '出庭；起诉', 'brumasser': '下毛毛雨；起薄雾', 'ravoir': '重新得到',
    'sourdre': '涌出；发源', 'saouler': '使喝醉', 'soûler': '使喝醉',
    'manoeuvrer': '操纵；调动', 'infiltrer': '渗透；渗入', 'river': '铆接；铆住',
    'chaloir': '关系；要紧', 'seoir': '适合；相称', 'échoir': '到期；轮到',
    'déchoir': '衰落；堕落', 'oindre': '涂油；敷圣油', 'amuïr': '（语音）脱落；不再发音',
    'chauvir': '竖起耳朵', 'apparoir': '（法律）显见', 'forclore': '（法律）失权；除斥',
    'occlure': '闭塞；封闭', 'receper': '平茬；截干', 'recéper': '平茬；截干',
}

MOJIBAKE = re.compile(r'[�]|Ã[\x80-\xbf]|â€')
CJK = re.compile(r'[一-鿿]')
PLACEHOLDER = re.compile(r'^(\?+|todo|n/?a|null|none|-+|\(n\))$', re.IGNORECASE)


# --------------------------------------------------------------------------
# Verbiste
# --------------------------------------------------------------------------

def parse_templates(path):
    """conjugation-fr.xml -> {template_name: {tense_key: [ [alt, ...], ... ]}}"""
    root = ET.parse(path).getroot()
    templates = {}
    for tpl in root:
        name = tpl.get('name')
        table = {}
        for section in tpl:
            for tense in section:
                key = '%s.%s' % (section.tag, tense.tag)
                slots = []
                for p in tense:
                    # <p/> with no <i> child = the verb has no form here
                    # (defective).  <p><i/></p> means "stem + empty ending",
                    # which is a real form: "il bat", "il vêt", "nui".
                    alts = [(i.text or '').strip() for i in p]
                    slots.append(alts if len(p) else [])
                table[key] = slots
        templates[name] = table
    return templates


def parse_verbs(path):
    """verbs-fr.xml -> ({infinitive: template}, {infinitive: aspirate_h})"""
    root = ET.parse(path).getroot()
    mapping = OrderedDict()
    aspirate = {}
    for v in root:
        inf = (v.find('i').text or '').strip()
        tpl = (v.find('t').text or '').strip()
        if not inf or not tpl:
            continue
        mapping[inf] = tpl
        if v.find('aspirate-h') is not None:
            aspirate[inf] = True
    return mapping, aspirate


PREFIXES = ['re', 'ré', 'dé', 'des', 'dés', 'entre', 'contre', 'sur', 'sous',
            'in', 'em', 'en', 'pré', 'pro', 'trans', 'mal', 'co', 'a']

# Verbs with two complete, equally correct paradigms.  Both are generated and
# merged as alternatives (asseoir: j'assieds / j'assois).
VARIANT_INFINITIVES = {
    'asseoir': 'assoir',
    'rasseoir': 'rassoir',
    'surseoir': 'sursoir',
}

# Reviewed additions where Verbiste keeps only one of two standard forms.
EXTRA_FORMS = {
    ('vouloir', 'imperatif_present'): {'tu': ['veux'], 'nous': ['voulons'], 'vous': ['voulez']},
    ('fleurir', 'participe_present'): {'_': ['fleurissant']},
}

# Verbiste's croître-family templates are internally inconsistent about the
# circumflex.  These two slots are replaced outright; both replacements are
# backed by Lexique 3.83 *and* by the French Wiktionary table, which agree
# against Verbiste.  (croître carries the circumflex in every form that would
# otherwise be homographic with croire -- "croîs" -- while accroître carries it
# only before -t, so "j'accrois / tu accrois / il accroît".)
FORM_OVERRIDES = {
    # (base infinitive, tense key, person): replacement
    ('croître', 'imperatif_present', 'tu'): ['croîs'],
    ('accroître', 'indicatif_present', 'tu'): ['accrois', 'accroîs'],
}

# Impersonal verbs whose Verbiste model is a fully personal one.  Value = the
# person slots that do not exist; detected by comparing every dataset verb
# against the French Wiktionary table, which dashes the missing cells.
# (falloir/pleuvoir need no entry: Verbiste already leaves their slots empty.)
IMPERSONAL = {
    'neiger': ('je', 'tu', 'nous', 'vous', 'ils_elles'),
}


def template_for(inf, mapping):
    """Verbiste template, falling back to prefix stripping (refaire -> faire)."""
    if inf in mapping:
        return mapping[inf], 'verbiste'
    for pref in PREFIXES:
        if inf.startswith(pref) and len(inf) > len(pref) + 3:
            base = inf[len(pref):]
            if base in mapping:
                return mapping[base], 'verbiste+prefix'
    return None, None


# --------------------------------------------------------------------------
# The conjugation engine
# --------------------------------------------------------------------------

TENSE_SOURCE = {
    'indicatif_present': 'indicative.present',
    'indicatif_imparfait': 'indicative.imperfect',
    'indicatif_passe_simple': 'indicative.simple-past',
    'indicatif_futur_simple': 'indicative.future',
    'conditionnel_present': 'conditional.present',
    'subjonctif_present': 'subjunctive.present',
    'subjonctif_imparfait': 'subjunctive.imperfect',
}
SUBJUNCTIVE_PREFIXED = {'subjonctif_present', 'subjonctif_imparfait'}


def apply_template(infinitive, tpl_name, templates):
    """Return {tense_key: [ [alternatives], x6 ]} of raw simple forms."""
    ending = tpl_name.split(':', 1)[1]
    if not infinitive.endswith(ending):
        raise ValueError('template %s does not fit %s' % (tpl_name, infinitive))
    stem = infinitive[:len(infinitive) - len(ending)]
    table = templates[tpl_name]
    out = {}
    for key, slots in table.items():
        out[key] = [[stem + a for a in alts] for alts in slots]
    return out


def join_alts(alts):
    seen = []
    for a in alts:
        if a and a not in seen:
            seen.append(a)
    return '/'.join(seen)


def person_forms(slots):
    """slots: list of 6 alternative-lists -> {person: 'a/b'}"""
    return OrderedDict((p, join_alts(slots[i]) if i < len(slots) else '')
                       for i, p in enumerate(PERSONS))


def reflexive_prefix(person, word):
    pron = REFLEXIVE_PRONOUN[person]
    if pron in ('me', 'te', 'se') and VOWEL_START.match(word or ''):
        return pron[0] + "'" + word
    return pron + ' ' + word


# --------------------------------------------------------------------------
# Glosses
# --------------------------------------------------------------------------

POS_LINE = re.compile(r'^\s*(?:\[[^\]]*\]|[a-zA-Z]{1,6}\.)\s*')
PARENS = re.compile(r'\([^)]*\)')


def clean_english(glosses):
    out = []
    for g in glosses:
        g = re.sub(r'\s+', ' ', g).strip().rstrip('.')
        # Wiktionary appends a long parenthetical clarifier to many glosses
        # ("to purr (to make a vibrating sound ...)").  Keep the head.
        core = re.sub(r'\s*\([^()]*\)\s*$', '', g).strip()
        if core:
            g = core
        if not g or len(g) > 90:
            continue
        if g.lower().startswith(('alternative spelling', 'obsolete spelling',
                                 'misspelling', 'pre-1990', 'post-1990',
                                 'alternative form', 'archaic form', 'dated form',
                                 'eye dialect', 'nonstandard spelling')):
            continue
        out.append(g)
        if len(out) == 2 or sum(len(x) + 2 for x in out) > 60:
            break
    text = '; '.join(out)
    if len(text) > 80:
        text = out[0][:80]
    return text


def english_pivot_keys(glosses):
    """Candidate English dictionary keys extracted from Wiktionary glosses."""
    keys = []
    for g in glosses:
        g = PARENS.sub(' ', g)
        for piece in re.split(r'[;,]', g):
            piece = piece.strip().lower()
            piece = re.sub(r'^to\s+', '', piece)
            piece = re.sub(r'[^a-z\s\-]', '', piece).strip()
            if not piece:
                continue
            if piece not in keys:
                keys.append(piece)
            head = piece.split()[0]
            if head and head not in keys:
                keys.append(head)
    return keys[:14]


def ecdict_chinese(cur, cache, key):
    if key in cache:
        return cache[key]
    cur.execute('SELECT translation, pos FROM stardict WHERE word = ? COLLATE NOCASE LIMIT 1', (key,))
    row = cur.fetchone()
    result = None
    if row and row[0]:
        verb_lines, other_lines = [], []
        for line in str(row[0]).split('\n'):
            line = line.strip()
            if not line or not CJK.search(line):
                continue
            is_verb = bool(re.match(r'^(v|vt|vi|va|aux)\.', line))
            body = POS_LINE.sub('', line).strip()
            body = body.strip(' ,;，；')
            if not body or not CJK.search(body):
                continue
            (verb_lines if is_verb else other_lines).append(body)
        chosen = verb_lines or other_lines
        if chosen:
            parts = []
            for body in chosen[:2]:
                bits = [b.strip() for b in re.split(r'[,，;；]', body) if b.strip()]
                parts.extend(bits[:3])
            parts = list(OrderedDict.fromkeys(parts))[:4]
            text = '；'.join(parts)
            if len(text) > 40:
                text = '；'.join(parts[:2])
            if len(text) > 40:
                text = text[:40]
            if CJK.search(text):
                result = text
    cache[key] = result
    return result


# --------------------------------------------------------------------------
# Quality gates
# --------------------------------------------------------------------------

def bad_text(value):
    if not value or not str(value).strip():
        return 'empty'
    v = str(value).strip()
    if MOJIBAKE.search(v):
        return 'mojibake'
    if PLACEHOLDER.match(v):
        return 'placeholder'
    if re.search(r'(.{3,}?)\1{2,}', v):
        return 'repetition'
    return None


# --------------------------------------------------------------------------
# Build
# --------------------------------------------------------------------------

def load_lexique(path):
    """Return (lemma -> frequency, (lemma, morph-tag) -> set(attested surface forms)).

    Adjective rows are indexed too, under the key (adjective-lemma, 'ADJ').  A
    past participle that has become an adjective ("résolu") is filed in Lexique
    under cgram=ADJ, so its feminine/plural agreement forms ("résolue",
    "résolues") never appear in the VER rows; without this they would look
    unattested and get dropped.
    """
    import csv
    freq = OrderedDict()
    forms = {}
    with open(path, encoding='utf-8') as f:
        for row in csv.DictReader(f, delimiter='\t'):
            if row['cgram'] == 'ADJ':
                forms.setdefault((row['lemme'], 'ADJ'), set()).add(row['ortho'])
                continue
            if row['cgram'] != 'VER':
                continue
            lemma = row['lemme']
            if lemma not in freq:
                try:
                    freq[lemma] = round(float(row['freqlemfilms2']) + float(row['freqlemlivres']), 2)
                except ValueError:
                    freq[lemma] = 0.0
            for tag in row['infover'].split(';'):
                tag = tag.strip()
                if tag:
                    forms.setdefault((lemma, tag), set()).add(row['ortho'])
    return freq, forms


def load_kaikki(path, cache_path, wanted, refresh=False):
    if os.path.exists(cache_path) and not refresh:
        with open(cache_path, encoding='utf-8') as f:
            return json.load(f)
    records = {}
    with open(path, encoding='utf-8') as f:
        for line in f:
            if '"pos": "verb"' not in line:
                continue
            try:
                d = json.loads(line)
            except Exception:
                continue
            if d.get('lang_code') != 'fr' or d.get('pos') != 'verb':
                continue
            word = d.get('word')
            if word not in wanted:
                continue
            head_args = set()
            for h in (d.get('head_templates') or []):
                for v in (h.get('args') or {}).values():
                    head_args.add(str(v))
            if 'verb form' in head_args:
                continue
            glosses = []
            tags = set()
            for s in d.get('senses', []):
                if s.get('form_of') or s.get('alt_of'):
                    continue
                st = set(s.get('tags') or [])
                if st & {'form-of', 'obsolete', 'archaic'}:
                    continue
                tags |= st
                for g in (s.get('glosses') or []):
                    g = g.strip()
                    if g and g not in glosses:
                        glosses.append(g)
            aux = set()
            wforms = {}
            for fm in (d.get('forms') or []):
                form = (fm.get('form') or '').strip()
                ftags = fm.get('tags') or []
                if 'multiword-construction' in ftags and 'infinitive' in ftags:
                    if form.startswith('être'):
                        aux.add('être')
                    elif form.startswith('avoir'):
                        aux.add('avoir')
                if fm.get('source') == 'conjugation' and form and 'table-tags' not in ftags:
                    wforms.setdefault('|'.join(sorted(ftags)), []).append(form)
            rec = records.setdefault(word, {'glosses': [], 'aux': [], 'tags': [], 'forms': {}})
            for g in glosses:
                if g not in rec['glosses']:
                    rec['glosses'].append(g)
            rec['aux'] = sorted(set(rec['aux']) | aux)
            rec['tags'] = sorted(set(rec['tags']) | tags)
            for k, v in wforms.items():
                rec['forms'].setdefault(k, [])
                for item in v:
                    if item not in rec['forms'][k]:
                        rec['forms'][k].append(item)
    with open(cache_path, 'w', encoding='utf-8') as f:
        json.dump(records, f, ensure_ascii=False)
    return records


def choose_auxiliary(inf, rec):
    """Return (auxiliary, alternative_or_None)."""
    aux = set(rec.get('aux') or []) if rec else set()
    if aux == {'être'}:
        return 'être', None
    if aux == {'avoir', 'être'}:
        if inf in ETRE_PREFERRED_FOR_DUAL:
            return 'être', 'avoir'
        return 'avoir', 'être'
    if aux == {'avoir'}:
        if inf in ETRE_PREFERRED_FOR_DUAL:
            return 'être', 'avoir'
        return 'avoir', None
    # No Wiktionary evidence — fall back to the closed être class.
    if inf in ETRE_PREFERRED_FOR_DUAL:
        return 'être', 'avoir'
    return 'avoir', None


class Conjugator(object):
    def __init__(self, templates, verb_templates, aspirate, lex_forms=None):
        self.templates = templates
        self.verb_templates = verb_templates
        self.aspirate = aspirate
        self.lex_forms = lex_forms or {}
        self.aux_tables = {}

    def simple(self, infinitive):
        tpl, origin = template_for(infinitive, self.verb_templates)
        if not tpl:
            return None, None, None
        raw = apply_template(infinitive, tpl, self.templates)
        variant = VARIANT_INFINITIVES.get(infinitive)
        if variant:
            vtpl, _o = template_for(variant, self.verb_templates)
            if vtpl:
                vraw = apply_template(variant, vtpl, self.templates)
                for key, slots in vraw.items():
                    base = raw.get(key) or []
                    merged = []
                    for i in range(max(len(base), len(slots))):
                        a = list(base[i]) if i < len(base) else []
                        for x in (slots[i] if i < len(slots) else []):
                            if x not in a:
                                a.append(x)
                        merged.append(a)
                    raw[key] = merged
                tpl = '%s + %s' % (tpl, vtpl)
        return raw, tpl, origin

    def aux_table(self, aux):
        if aux not in self.aux_tables:
            raw, _tpl, _o = self.simple(aux)
            self.aux_tables[aux] = raw
        return self.aux_tables[aux]

    # -- helpers ------------------------------------------------------------
    @staticmethod
    def participles(raw):
        slots = raw.get('participle.past-participle') or []
        def pick(i):
            return slots[i][0] if i < len(slots) and slots[i] else ''
        ms, mp, fs, fp = pick(0), pick(1), pick(2), pick(3)
        return {'ms': ms, 'fs': fs, 'mp': mp, 'fp': fp}

    @staticmethod
    def agreement_for(person, pp):
        if person in ('je', 'tu', 'il_elle_on'):
            cand = [pp['ms'], pp['fs']]
        elif person == 'nous':
            cand = [pp['mp'], pp['fp']]
        elif person == 'ils_elles':
            cand = [pp['mp'], pp['fp']]
        else:  # vous: polite singular or plural, either gender
            cand = [pp['ms'], pp['fs'], pp['mp'], pp['fp']]
        return [c for c in cand if c]

    @staticmethod
    def person_mask(raw):
        """Which persons this verb has at all (impersonal verbs only have il)."""
        mask = [False] * 6
        for key in ('indicative.present', 'indicative.imperfect', 'indicative.future',
                    'indicative.simple-past', 'conditional.present',
                    'subjunctive.present', 'subjunctive.imperfect'):
            for idx, alts in enumerate(raw.get(key) or []):
                if idx < 6 and alts:
                    mask[idx] = True
        return mask

    def compound_person(self, aux_slots, pp, auxiliary, reflexive, mask=None):
        """aux_slots: 6 alternative-lists of the auxiliary's simple tense."""
        forms = OrderedDict()
        for idx, person in enumerate(PERSONS):
            aux_alts = aux_slots[idx] if idx < len(aux_slots) else []
            if mask is not None and not mask[idx]:
                forms[person] = ''
                continue
            if not aux_alts:
                forms[person] = ''
                continue
            pieces = []
            if auxiliary == 'être':
                pps = self.agreement_for(person, pp)
            else:
                pps = [pp['ms']] if pp['ms'] else []
            for a in aux_alts:
                for participle in pps:
                    phrase = '%s %s' % (a, participle)
                    if reflexive:
                        phrase = reflexive_prefix(person, phrase)
                    pieces.append(phrase)
            forms[person] = join_alts(pieces)
        return forms


LEX_TAG = {
    'indicatif_present': 'ind:pre', 'indicatif_imparfait': 'ind:imp',
    'indicatif_passe_simple': 'ind:pas', 'indicatif_futur_simple': 'ind:fut',
    'conditionnel_present': 'cnd:pre', 'subjonctif_present': 'sub:pre',
    'subjonctif_imparfait': 'sub:imp',
}
LEX_PERSON = ['1s', '2s', '3s', '1p', '2p', '3p']
LEX_IMPERATIVE = {1: '2s', 3: '1p', 4: '2p'}


def strip_accents(text):
    return ''.join(c for c in unicodedata.normalize('NFD', text)
                   if unicodedata.category(c) != 'Mn')


def merge_attested(generated, attested):
    """Fold in a Lexique-attested spelling variant that differs only in accents.

    Verbiste ships the post-1990 spelling for the -éger family ("protègerai")
    while the corpus overwhelmingly has the traditional one ("protégerai").
    Both are correct, so both are accepted.  The extra variant only takes the
    lead when Verbiste's own form is unattested in the corpus; otherwise it is
    appended, so marginal variants ("eussé", used only in "eussé-je") never
    displace the citation form ("eusse").
    """
    if not attested:
        return generated
    extra = [a for a in sorted(attested)
             if a not in generated
             and any(strip_accents(a) == strip_accents(g) for g in generated)]
    if not extra:
        return generated
    if any(g in attested for g in generated):
        return generated + extra
    return extra + [g for g in generated if g not in extra]


def build_verb(conj, infinitive, base_infinitive, meta):
    """meta: dict(rank, frequency, corpusRank, english, chinese, auxiliary,
                  auxiliaryAlt, reflexive, aspirateH, model)"""
    raw, tpl, origin = conj.simple(base_infinitive)
    if raw is None:
        return None
    reflexive = meta['reflexive']
    auxiliary = meta['auxiliary']
    pp = conj.participles(raw)
    if (auxiliary == 'être' or reflexive) and pp['ms']:
        # être-conjugated participles must agree, and Verbiste sometimes ships
        # only the masculine singular (fu:ir -> "enfui").  Agreement is fully
        # regular: add -e / -s / -es, with no doubling after -s/-x/-e.
        ms = pp['ms']
        if not pp['fs']:
            pp['fs'] = ms if ms.endswith('e') else ms + 'e'
        if not pp['mp']:
            pp['mp'] = ms if ms.endswith(('s', 'x')) else ms + 's'
        if not pp['fp']:
            pp['fp'] = pp['fs'] if pp['fs'].endswith('s') else pp['fs'] + 's'
    lex = conj.lex_forms
    attested_pp = set(lex.get((base_infinitive, 'par:pas')) or ())
    attested_pp |= set(lex.get((pp['ms'], 'ADJ')) or ())
    if auxiliary != 'être' and not reflexive:
        # An intransitive avoir-verb has no agreeing participle: Verbiste emits
        # "dormie/dormis/dormies" and "plue/plues" mechanically and those are
        # not French.  Only the masculine singular is unconditionally safe, so
        # the agreement forms are kept exactly when the corpus attests them.
        for slot in ('fs', 'mp', 'fp'):
            if pp[slot] and pp[slot] not in attested_pp:
                pp[slot] = ''
    aux_raw = conj.aux_table(auxiliary)
    mask = conj.person_mask(raw)

    tenses = OrderedDict()

    def add_person(key, group, label, slots, apply_reflexive=True, lex_tag=None):
        built = OrderedDict()
        for idx, person in enumerate(PERSONS):
            alts = list(slots[idx]) if idx < len(slots) else []
            if lex_tag and alts:
                alts = merge_attested(
                    alts, lex.get((base_infinitive, '%s:%s' % (lex_tag, LEX_PERSON[idx]))))
            override = FORM_OVERRIDES.get((base_infinitive, key, person))
            if override is not None:
                alts = list(override)
            for x in (EXTRA_FORMS.get((base_infinitive, key), {}).get(person) or []):
                if x not in alts and alts:
                    alts.append(x)
            words = []
            for a in alts:
                w = a
                if reflexive and apply_reflexive:
                    w = reflexive_prefix(person, w)
                words.append(w)
            built[person] = join_alts(words)
        if not any(built.values()):
            return
        tenses[key] = OrderedDict([
            ('type', 'person'), ('group_label', group), ('tense_label', label),
            ('forms', built),
        ])

    def add_single(key, group, label, values):
        vals = [v for v in values if v]
        if not vals:
            return
        tenses[key] = OrderedDict([
            ('type', 'single'), ('group_label', group), ('tense_label', label),
            ('forms', vals),
        ])

    # --- simple tenses ----------------------------------------------------
    add_person('indicatif_present', 'Indicatif', 'Présent', raw['indicative.present'],
               lex_tag='ind:pre')
    add_person('indicatif_imparfait', 'Indicatif', 'Imparfait', raw['indicative.imperfect'],
               lex_tag='ind:imp')
    add_person('indicatif_passe_simple', 'Indicatif', 'Passé simple', raw['indicative.simple-past'],
               lex_tag='ind:pas')
    add_person('indicatif_futur_simple', 'Indicatif', 'Futur simple', raw['indicative.future'],
               lex_tag='ind:fut')
    add_person('conditionnel_present', 'Conditionnel', 'Présent', raw['conditional.present'],
               lex_tag='cnd:pre')
    add_person('subjonctif_present', 'Subjonctif', 'Présent', raw['subjunctive.present'],
               lex_tag='sub:pre')
    add_person('subjonctif_imparfait', 'Subjonctif', 'Imparfait', raw['subjunctive.imperfect'],
               lex_tag='sub:imp')

    # --- compound tenses --------------------------------------------------
    compounds = [
        ('indicatif_passe_compose', 'Indicatif', 'Passé composé', 'indicative.present'),
        ('indicatif_plus_que_parfait', 'Indicatif', 'Plus-que-parfait', 'indicative.imperfect'),
        ('indicatif_passe_anterieur', 'Indicatif', 'Passé antérieur', 'indicative.simple-past'),
        ('indicatif_futur_anterieur', 'Indicatif', 'Futur antérieur', 'indicative.future'),
        ('conditionnel_passe', 'Conditionnel', 'Passé', 'conditional.present'),
        ('subjonctif_passe', 'Subjonctif', 'Passé', 'subjunctive.present'),
        ('subjonctif_plus_que_parfait', 'Subjonctif', 'Plus-que-parfait', 'subjunctive.imperfect'),
    ]
    for key, group, label, aux_key in compounds:
        forms = conj.compound_person(aux_raw[aux_key], pp, auxiliary, reflexive, mask)
        if not any(forms.values()):
            continue
        tenses[key] = OrderedDict([
            ('type', 'person'), ('group_label', group), ('tense_label', label),
            ('forms', forms),
        ])

    # --- impératif --------------------------------------------------------
    imp = raw.get('imperative.imperative-present') or []
    imp_slots = [[], imp[0] if len(imp) > 0 else [], [],
                 imp[1] if len(imp) > 1 else [], imp[2] if len(imp) > 2 else [], []]
    if reflexive:
        suffix = {'tu': '-toi', 'nous': '-nous', 'vous': '-vous'}
        built = OrderedDict()
        for idx, person in enumerate(PERSONS):
            alts = imp_slots[idx]
            built[person] = join_alts([a + suffix[person] for a in alts]) if alts else ''
        if any(built.values()):
            tenses['imperatif_present'] = OrderedDict([
                ('type', 'person'), ('group_label', 'Impératif'), ('tense_label', 'Présent'),
                ('forms', built),
            ])
    else:
        add_person('imperatif_present', 'Impératif', 'Présent', imp_slots)
        aux_imp = aux_raw.get('imperative.imperative-present') or []
        aux_imp_slots = [[], aux_imp[0] if len(aux_imp) > 0 else [], [],
                         aux_imp[1] if len(aux_imp) > 1 else [],
                         aux_imp[2] if len(aux_imp) > 2 else [], []]
        built = OrderedDict()
        for idx, person in enumerate(PERSONS):
            alts = aux_imp_slots[idx]
            if not alts:
                built[PERSONS[idx]] = ''
                continue
            pps = (Conjugator.agreement_for(PERSONS[idx], pp) if auxiliary == 'être'
                   else ([pp['ms']] if pp['ms'] else []))
            built[PERSONS[idx]] = join_alts(['%s %s' % (a, p) for a in alts for p in pps])
        if any(built.values()) and tenses.get('imperatif_present'):
            tenses['imperatif_passe'] = OrderedDict([
                ('type', 'person'), ('group_label', 'Impératif'), ('tense_label', 'Passé'),
                ('forms', built),
            ])

    # --- non-finite -------------------------------------------------------
    pres_part = (raw.get('participle.present-participle') or [[]])
    pres_part = list(pres_part[0]) if pres_part else []
    for x in (EXTRA_FORMS.get((base_infinitive, 'participe_present'), {}).get('_') or []):
        if x not in pres_part:
            pres_part.insert(0, x)
    pres_part = merge_attested(pres_part, lex.get((base_infinitive, 'par:pre')))
    pp_values = []
    for a in pres_part:
        pp_values.append(reflexive_prefix('il_elle_on', a) if reflexive else a)
    add_single('participe_present', 'Participe', 'Présent', pp_values)

    ordered_pp = merge_attested([v for v in (pp['ms'], pp['fs'], pp['mp'], pp['fp']) if v],
                                attested_pp)
    add_single('participe_passe', 'Participe', 'Passé', list(OrderedDict.fromkeys(ordered_pp)))

    inf_present = infinitive
    add_single('infinitif_present', 'Infinitif', 'Présent', [inf_present])
    if auxiliary == 'être':
        pieces = ['être %s' % v for v in OrderedDict.fromkeys(
            [pp['ms'], pp['fs'], pp['mp'], pp['fp']]) if v]
    else:
        pieces = ['avoir %s' % pp['ms']] if pp['ms'] else []
    if reflexive:
        pieces = [reflexive_prefix('il_elle_on', p) for p in pieces]
    add_single('infinitif_passe', 'Infinitif', 'Passé', pieces)

    # --- impersonal verbs -------------------------------------------------
    # Verbiste runs "neiger" through the ordinary -ger model and happily emits
    # "je neige".  Wiktionary dashes those cells, and they are not French.
    # Blank them everywhere; the gap declaration below then records them.
    dead = IMPERSONAL.get(base_infinitive)
    if dead:
        for key, t in list(tenses.items()):
            if t['type'] != 'person':
                continue
            for person in dead:
                t['forms'][person] = ''
            if not any(t['forms'].values()):
                del tenses[key]

    # A verb with no past participle (renaître, poindre, bruire) is genuinely
    # defective: it simply has no compound tenses.  Keep it for its simple
    # tenses rather than dropping it, but insist on a usable paradigm.
    finite = sum(1 for t in tenses.values() if t['type'] == 'person')
    if len(tenses) < 3 or finite < 1:
        return None

    entry = OrderedDict()
    entry['rank'] = meta['rank']
    entry['infinitive'] = infinitive
    entry['frequency'] = meta['frequency']
    entry['corpusRank'] = meta['corpusRank']
    entry['english'] = meta['english']
    entry['chinese'] = meta['chinese']
    entry['partOfSpeech'] = 'verbe pronominal' if reflexive else 'verbe'
    entry['model'] = tpl
    entry['auxiliary'] = auxiliary
    if meta.get('auxiliaryAlt'):
        entry['auxiliaryAlt'] = meta['auxiliaryAlt']
    if reflexive:
        entry['reflexive'] = True
        entry['frequencyBasis'] = 'Lexique lemma frequency of the base verb "%s"' % base_infinitive
    if meta.get('aspirateH'):
        entry['aspirateH'] = True
    missing = [k for k in CANONICAL_TENSES if k not in tenses]
    if missing:
        # Declared, not silently absent: falloir has no plural, renaître has no
        # past participle, pouvoir has no imperative.  The validator checks that
        # a tense is missing only when it is listed here.
        entry['defective'] = missing
    gaps = OrderedDict()
    for key, t in tenses.items():
        if t['type'] != 'person':
            continue
        empty = [p for p in PERSONS if not t['forms'][p]]
        if key.startswith('imperatif'):
            empty = [p for p in empty if p in ('tu', 'nous', 'vous')]
        if empty:
            gaps[key] = empty
    if gaps:
        # Every person slot that is legitimately empty, declared per tense:
        # falloir is impersonal, clore has no "nous/vous" present, pleuvoir has
        # no plural past historic.  The validator refuses any undeclared hole.
        entry['gaps'] = gaps
    entry['participle'] = OrderedDict([('ms', pp['ms']), ('fs', pp['fs']),
                                       ('mp', pp['mp']), ('fp', pp['fp'])])
    entry['source'] = SOURCE_LABEL
    entry['tenses'] = tenses
    return entry


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--work', default='/tmp/frconj')
    ap.add_argument('--limit', type=int, default=1800)
    ap.add_argument('--refresh-cache', action='store_true')
    ap.add_argument('--out', default=OUT_PATH)
    args = ap.parse_args()

    work = args.work
    need = {
        'verbiste': os.path.join(work, 'verbiste-0.1.49', 'data'),
        'lexique': os.path.join(work, 'Lexique383.tsv'),
        'kaikki': os.path.join(work, 'fr-verbs.jsonl'),
        'ecdict': os.path.join(work, 'stardict.db'),
    }
    for label, path in need.items():
        if not os.path.exists(path):
            sys.exit('missing %s at %s\nDownload:%s' % (label, path, DOWNLOADS))

    templates = parse_templates(os.path.join(need['verbiste'], 'conjugation-fr.xml'))
    verb_templates, aspirate = parse_verbs(os.path.join(need['verbiste'], 'verbs-fr.xml'))
    print('verbiste: %d model paradigms, %d infinitives' % (len(templates), len(verb_templates)))

    freq, lex_forms = load_lexique(need['lexique'])
    ordered = sorted(freq.items(), key=lambda kv: (-kv[1], kv[0]))
    corpus_rank = {lemma: i + 1 for i, (lemma, _f) in enumerate(ordered)}
    print('lexique: %d verb lemmas, %d (lemma, morph-tag) attestations'
          % (len(ordered), len(lex_forms)))

    conj = Conjugator(templates, verb_templates, aspirate, lex_forms)

    candidates = []
    for lemma, f in ordered:
        tpl, origin = template_for(lemma, verb_templates)
        if tpl:
            candidates.append((lemma, f, origin))
    print('conjugatable candidates: %d' % len(candidates))

    wanted = set(l for l, _f, _o in candidates[:args.limit * 3])
    wanted |= {'avoir', 'être'}
    wanted |= set(base for _s, base, _e, _c in PRONOMINAL_VERBS)
    kaikki = load_kaikki(need['kaikki'], os.path.join(work, 'fr-verb-kaikki-cache.json'),
                         wanted, refresh=args.refresh_cache)
    print('kaikki records for candidates: %d' % len(kaikki))

    db = sqlite3.connect(need['ecdict'])
    cur = db.cursor()
    zh_cache = {}

    stats = Counter()
    picked = []
    rejects = []

    def try_build(lemma, f):
        """Run the quality gate; return an entry or None (and log why)."""
        rec = kaikki.get(lemma)
        if not rec:
            if lemma not in MANUAL_ENGLISH:
                stats['no_wiktionary_entry'] += 1
                rejects.append((lemma, 'no_wiktionary_entry'))
                return None
            rec = {'glosses': [], 'aux': None, 'forms': []}
        english = MANUAL_ENGLISH.get(lemma) or clean_english(rec['glosses'])
        if bad_text(english) or len(english) < 2:
            stats['no_english_gloss'] += 1
            rejects.append((lemma, 'no_english_gloss'))
            return None
        if english.strip().lower() == lemma.lower():
            stats['gloss_is_headword'] += 1
            rejects.append((lemma, 'gloss_is_headword'))
            return None
        chinese = MANUAL_CHINESE.get(lemma) or MANUAL_ENGLISH_ZH.get(lemma)
        if not chinese:
            for key in english_pivot_keys(rec['glosses']):
                chinese = ecdict_chinese(cur, zh_cache, key)
                if chinese:
                    break
        if not chinese or bad_text(chinese) or not CJK.search(chinese):
            stats['no_chinese_gloss'] += 1
            rejects.append((lemma, 'no_chinese_gloss'))
            return None
        aux, aux_alt = choose_auxiliary(lemma, rec)
        meta = {
            'rank': 0, 'frequency': f, 'corpusRank': corpus_rank[lemma],
            'english': english, 'chinese': chinese, 'auxiliary': aux,
            'auxiliaryAlt': aux_alt, 'reflexive': False,
            'aspirateH': bool(aspirate.get(lemma)),
        }
        entry = build_verb(conj, lemma, lemma, meta)
        if entry is None:
            stats['conjugation_failed'] += 1
            rejects.append((lemma, 'conjugation_failed'))
            return None
        return entry

    for lemma, f, origin in candidates:
        if len(picked) >= args.limit:
            break
        if lemma in PRONOMINAL_ONLY:
            stats['skipped_pronominal_only'] += 1
            continue
        entry = try_build(lemma, f)
        if entry is None:
            continue
        picked.append(entry)
        stats['accepted'] += 1
        stats['origin_' + origin] += 1

    # --- model-paradigm supplement ---------------------------------------
    # Pure corpus frequency leaves ~47 of Verbiste's 148 model paradigms with
    # no representative (moudre, éclore, prévaloir, ...).  A conjugation
    # trainer should be able to show every Bescherelle pattern, so for each
    # still-uncovered model we add exactly one verb: its most frequent member,
    # and only if it clears the same gloss gate.  Nothing is added to hit a
    # count -- the supplement stops as soon as every model has a representative.
    picked_names = set(e['infinitive'] for e in picked)
    covered = set()
    # pronominal entries are appended below but already cover their base model
    for lemma in picked_names | set(b for _s, b, _e, _c in PRONOMINAL_VERBS):
        tpl, _ = template_for(lemma, verb_templates)
        if tpl:
            covered.add(tpl)
    for lemma, f, origin in candidates:
        if lemma in picked_names or lemma in PRONOMINAL_ONLY:
            continue
        tpl, _ = template_for(lemma, verb_templates)
        if not tpl or tpl in covered:
            continue
        entry = try_build(lemma, f)
        if entry is None:
            continue
        covered.add(tpl)
        picked.append(entry)
        picked_names.add(lemma)
        stats['accepted_model_coverage'] += 1

    # --- pronominal verbs -------------------------------------------------
    for surface, base, en, zh in PRONOMINAL_VERBS:
        tpl, origin = template_for(base, verb_templates)
        if not tpl:
            stats['pronominal_no_template'] += 1
            continue
        meta = {
            'rank': 0,
            'frequency': freq.get(base, 0.0),
            'corpusRank': corpus_rank.get(base, 0),
            'english': en, 'chinese': zh,
            'auxiliary': 'être', 'auxiliaryAlt': None, 'reflexive': True,
            'aspirateH': bool(aspirate.get(base)),
        }
        entry = build_verb(conj, surface, base, meta)
        if entry is None:
            stats['pronominal_failed'] += 1
            continue
        picked.append(entry)
        stats['accepted_pronominal'] += 1

    # rank = position in this dataset ordered by real corpus frequency
    picked.sort(key=lambda e: (-e['frequency'], e['infinitive']))
    seen = set()
    unique = []
    for e in picked:
        if e['infinitive'] in seen:
            continue
        seen.add(e['infinitive'])
        unique.append(e)
    for i, e in enumerate(unique):
        e['rank'] = i + 1
    picked = unique

    total_forms = 0
    for e in picked:
        for t in e['tenses'].values():
            vals = t['forms'].values() if isinstance(t['forms'], dict) else t['forms']
            total_forms += sum(1 for v in vals if v)

    header = (
        '// French conjugation dataset — auto-generated by\n'
        '// scripts/build_french_conjugations.py.  DO NOT EDIT BY HAND.\n'
        '//\n'
        '// Verbs: %d   Tense/mood groups: up to %d   Non-empty forms: %d\n'
        '//\n'
        '// Sources and licences:\n'
        '//   * Verbiste 0.1.49 conjugation templates — GPL-2+ (Pierre Sarrazin)\n'
        '//   * Lexique 3.83 lemma frequencies — CC BY-SA 4.0 (lexique.org)\n'
        '//   * English Wiktionary via Wiktextract/kaikki.org — CC BY-SA 4.0 / GFDL\n'
        '//     (English glosses + auxiliary selection + cross-validation forms)\n'
        '//   * ECDICT 1.0.28 — English→Chinese pivot for the Chinese gloss\n'
        '//\n'
        '// Subject-pronoun elision is NOT baked in: "ai" is stored under the "je"\n'
        '// key and the app renders "j\'ai".  `aspirateH: true` marks verbs whose\n'
        '// initial h blocks elision (je hais).  Reflexive-pronoun elision\n'
        '// ("m\'appelle") is part of the form and IS stored.\n'
        % (len(picked), max(len(e['tenses']) for e in picked), total_forms)
    )

    body = json.dumps(picked, ensure_ascii=False, separators=(',', ':'))
    js = (header +
          '\n(function () {\n  \'use strict\';\n\n'
          '  const FRENCH_CONJUGATION_DATA = ' + body + ';\n\n'
          '  if (typeof window !== \'undefined\') {\n'
          '    window.FRENCH_CONJUGATION_DATA = FRENCH_CONJUGATION_DATA;\n  }\n\n'
          '  if (typeof module !== \'undefined\' && module.exports) {\n'
          '    module.exports = FRENCH_CONJUGATION_DATA;\n  }\n})();\n')
    with open(args.out, 'w', encoding='utf-8') as f:
        f.write(js)

    print('wrote %s (%.1f MB)' % (args.out, os.path.getsize(args.out) / 1e6))
    print('verbs: %d, non-empty forms: %d' % (len(picked), total_forms))
    print('stats:', dict(sorted(stats.items())))
    aux_counter = Counter(e['auxiliary'] for e in picked)
    print('auxiliary distribution:', dict(aux_counter))
    tense_counter = Counter(len(e['tenses']) for e in picked)
    print('tense-group counts:', dict(sorted(tense_counter.items())))
    models = set()
    for e in picked:
        models.update(e['model'].split(' + '))
    print('model paradigms represented: %d of %d' % (len(models), len(templates)))
    print('rejected candidates: %d -> %s' % (len(rejects), rejects))

    # side-car report used by the validator for cross-checking
    with open(os.path.join(work, 'build-report.json'), 'w', encoding='utf-8') as f:
        json.dump({'stats': dict(stats), 'verbs': len(picked), 'forms': total_forms,
                   'models': len(models), 'rejects': rejects},
                  f, ensure_ascii=False, indent=1)


if __name__ == '__main__':
    main()
