#!/usr/bin/env python3
"""Build German verb conjugation data for the static app.

German correctness policy:
- finite simple stems come from vetted overrides or the principal parts in
  data/german-vocabulary.js notes when available;
- weak regular verbs are generated by standard German endings;
- separable-prefix verbs are skipped unless handled explicitly, because
  finite main-clause placement cannot be represented by a simple suffix rule.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
VOCAB_PATH = ROOT / "data" / "german-vocabulary.js"
OUT_PATH = ROOT / "data" / "german-conjugations.js"
TARGET_COUNT = 300
MANDATORY = ("sein", "haben", "werden", "gehen", "können", "fahren")

PERSONS = ["ich", "du", "er_sie_es", "wir", "ihr", "sie"]

try:
    from wordfreq import zipf_frequency
except Exception:  # pragma: no cover - fallback for offline environments.
    zipf_frequency = None


@dataclass
class Parts:
    present: list[str]
    preterite: list[str]
    partizip_ii: str
    aux: tuple[str, ...] = ("haben",)
    confidence: str = "generated"


MANUAL: dict[str, Parts] = {
    "sein": Parts(
        ["bin", "bist", "ist", "sind", "seid", "sind"],
        ["war", "warst", "war", "waren", "wart", "waren"],
        "gewesen",
        ("sein",),
        "manual: Reverso/Wiktionary spot-checked",
    ),
    "haben": Parts(
        ["habe", "hast", "hat", "haben", "habt", "haben"],
        ["hatte", "hattest", "hatte", "hatten", "hattet", "hatten"],
        "gehabt",
        ("haben",),
        "manual: Reverso/Wiktionary spot-checked",
    ),
    "werden": Parts(
        ["werde", "wirst", "wird", "werden", "werdet", "werden"],
        ["wurde", "wurdest", "wurde", "wurden", "wurdet", "wurden"],
        "geworden",
        ("sein",),
        "manual: Reverso/Wiktionary spot-checked",
    ),
    "können": Parts(
        ["kann", "kannst", "kann", "können", "könnt", "können"],
        ["konnte", "konntest", "konnte", "konnten", "konntet", "konnten"],
        "gekonnt",
        ("haben",),
        "manual modal",
    ),
    "müssen": Parts(
        ["muss", "musst", "muss", "müssen", "müsst", "müssen"],
        ["musste", "musstest", "musste", "mussten", "musstet", "mussten"],
        "gemusst",
        ("haben",),
        "manual modal",
    ),
    "dürfen": Parts(
        ["darf", "darfst", "darf", "dürfen", "dürft", "dürfen"],
        ["durfte", "durftest", "durfte", "durften", "durftet", "durften"],
        "gedurft",
        ("haben",),
        "manual modal",
    ),
    "wollen": Parts(
        ["will", "willst", "will", "wollen", "wollt", "wollen"],
        ["wollte", "wolltest", "wollte", "wollten", "wolltet", "wollten"],
        "gewollt",
        ("haben",),
        "manual modal",
    ),
    "sollen": Parts(
        ["soll", "sollst", "soll", "sollen", "sollt", "sollen"],
        ["sollte", "solltest", "sollte", "sollten", "solltet", "sollten"],
        "gesollt",
        ("haben",),
        "manual modal",
    ),
    "mögen": Parts(
        ["mag", "magst", "mag", "mögen", "mögt", "mögen"],
        ["mochte", "mochtest", "mochte", "mochten", "mochtet", "mochten"],
        "gemocht",
        ("haben",),
        "manual modal",
    ),
    "wissen": Parts(
        ["weiß", "weißt", "weiß", "wissen", "wisst", "wissen"],
        ["wusste", "wusstest", "wusste", "wussten", "wusstet", "wussten"],
        "gewusst",
        ("haben",),
        "manual irregular",
    ),
    "gehen": Parts(
        ["gehe", "gehst", "geht", "gehen", "geht", "gehen"],
        ["ging", "gingst", "ging", "gingen", "gingt", "gingen"],
        "gegangen",
        ("sein",),
        "manual: Reverso spot-checked",
    ),
    "fahren": Parts(
        ["fahre", "fährst", "fährt", "fahren", "fahrt", "fahren"],
        ["fuhr", "fuhrst", "fuhr", "fuhren", "fuhrt", "fuhren"],
        "gefahren",
        ("sein", "haben"),
        "manual: Reverso spot-checked",
    ),
}

SEIN_AUX_VERBS = {
    "bleiben",
    "fallen",
    "fliegen",
    "gehen",
    "gelangen",
    "geschehen",
    "kommen",
    "laufen",
    "passieren",
    "reisen",
    "rennen",
    "scheitern",
    "springen",
    "steigen",
    "sterben",
    "wachsen",
    "werden",
}

SEPARABLE_PREFIXES = (
    "ab",
    "an",
    "auf",
    "aus",
    "bei",
    "dar",
    "ein",
    "fern",
    "fest",
    "fort",
    "her",
    "hin",
    "los",
    "mit",
    "nach",
    "vor",
    "statt",
    "teil",
    "um",
    "weg",
    "weiter",
    "zu",
    "zurück",
    "zusammen",
)

INSEPARABLE_PREFIXES = ("be", "emp", "ent", "er", "ge", "miss", "ver", "zer")

SKIP_WORDS = {
    "einen",
    "sondern",
    "untern",
    "länden",
    "jungen",
    "stunden",
    "grünen",
    "schönen",
    "blauen",
    "erschienen",
    "gegessen",
    "richtigen",
    "rechten",
    "mengen",
    "leiben",
}


def load_js_array(path: Path, const_name: str) -> list[dict[str, Any]]:
    text = path.read_text(encoding="utf-8")
    match = re.search(rf"const\s+{re.escape(const_name)}\s*=\s*\[", text)
    if not match:
        raise ValueError(f"Could not find {const_name} in {path}")
    start = match.end() - 1
    depth = 0
    in_string = False
    escape = False
    for pos in range(start, len(text)):
        ch = text[pos]
        if in_string:
            if escape:
                escape = False
            elif ch == "\\":
                escape = True
            elif ch == '"':
                in_string = False
            continue
        if ch == '"':
            in_string = True
        elif ch == "[":
            depth += 1
        elif ch == "]":
            depth -= 1
            if depth == 0:
                return json.loads(text[start : pos + 1])
    raise ValueError(f"Could not parse array for {const_name} in {path}")


def normalize_spelling(text: str) -> str:
    replacements = {
        "muß": "muss",
        "Muß": "Muss",
        "gemußt": "gemusst",
        "wußte": "wusste",
        "gewußt": "gewusst",
        "läßt": "lässt",
        "vergißt": "vergisst",
        "daß": "dass",
    }
    for old, new in replacements.items():
        text = text.replace(old, new)
    return text.strip()


def clean_gloss(text: str) -> str:
    text = re.sub(r"\b(?:Vi|Vt|V|Vr|Adv|Präp|Konj|Pron|Art)\b\.?", "", text)
    text = re.sub(r"\([^)]*\)", "", text)
    text = re.sub(r"\s+", " ", text).strip(" ;,")
    return text.split(";")[0].split("；")[0][:80]


def german_frequency(word: str, rank: int) -> float:
    if zipf_frequency:
        return round(float(zipf_frequency(word, "de")), 4)
    return round(max(0.0, 7.0 - rank / 5000), 4)


def is_verb_entry(entry: dict[str, Any]) -> bool:
    word = str(entry.get("german", "")).lower()
    notes = str(entry.get("notes", ""))
    if word in SKIP_WORDS:
        return False
    if not re.fullmatch(r"[a-zäöüß]+", word):
        return False
    if not (word.endswith("en") or word.endswith("n")):
        return False
    return bool(re.search(r"(^|[ /])V(?:i|t|r)?(?:[ /().]|$)", notes))


def looks_separable(word: str, verb_lemmas: set[str]) -> bool:
    if word in MANUAL:
        return False
    for prefix in SEPARABLE_PREFIXES:
        if word.startswith(prefix) and len(word) > len(prefix) + 4:
            rest = word[len(prefix) :]
            if rest in verb_lemmas or rest in MANUAL or rest in globals().get("PRINCIPAL_OVERRIDES", {}):
                return True
    return False


def infinitive_stem(infinitive: str) -> str:
    if infinitive.endswith("eln") or infinitive.endswith("ern"):
        return infinitive[:-1]
    if infinitive.endswith("en"):
        return infinitive[:-2]
    if infinitive.endswith("n"):
        return infinitive[:-1]
    raise ValueError(f"Unsupported infinitive {infinitive}")


def needs_e(stem: str) -> bool:
    if stem.endswith(("d", "t")):
        return True
    return bool(re.search(r"(chn|ffn|gn|tm|dm)$", stem))


def is_sibilant(stem: str) -> bool:
    return stem.endswith(("s", "ss", "ß", "z", "x"))


def regular_present(infinitive: str) -> list[str]:
    if infinitive.endswith("eln"):
        stem = infinitive[:-1]
        ich = stem[:-2] + "le" if stem.endswith("el") else stem + "e"
        return [ich, stem + "st", stem + "t", infinitive, stem + "t", infinitive]
    if infinitive.endswith("ern"):
        stem = infinitive[:-1]
        return [stem + "e", stem + "st", stem + "t", infinitive, stem + "t", infinitive]

    stem = infinitive_stem(infinitive)
    if needs_e(stem):
        du = stem + "est"
        er = stem + "et"
        ihr = stem + "et"
    elif is_sibilant(stem):
        du = stem + "t"
        er = stem + "t"
        ihr = stem + "t"
    else:
        du = stem + "st"
        er = stem + "t"
        ihr = stem + "t"
    return [stem + "e", du, er, infinitive, ihr, infinitive]


def present_from_third(infinitive: str, third: str | None) -> list[str]:
    forms = regular_present(infinitive)
    if not third or third == forms[2]:
        return forms
    third = normalize_spelling(third)
    forms[2] = third
    if third.endswith("et"):
        forms[1] = third[:-1] + "st"
    elif third.endswith("t"):
        if infinitive_stem(infinitive).endswith("t"):
            forms[1] = third + "st"
        else:
            changed_stem = third[:-1]
            forms[1] = changed_stem + ("t" if is_sibilant(changed_stem) else "st")
    else:
        forms[1] = third + "st"
    return forms


def regular_participle(infinitive: str) -> str:
    stem = infinitive_stem(infinitive)
    suffix = "et" if needs_e(stem) else "t"
    if infinitive.endswith("ieren"):
        return infinitive[:-2] + "t"
    if infinitive.startswith(INSEPARABLE_PREFIXES) or infinitive.startswith(("über", "unter")):
        return stem + suffix
    return "ge" + stem + suffix


def weak_preterite_from_infinitive(infinitive: str) -> str:
    stem = infinitive_stem(infinitive)
    return stem + ("ete" if needs_e(stem) else "te")


def preterite_forms_from_singular(singular: str) -> list[str]:
    singular = normalize_spelling(singular)
    if singular.endswith("te"):
        return [singular, singular + "st", singular, singular + "n", singular + "t", singular + "n"]
    du_suffix = "est" if singular.endswith(("d", "t", "s", "ß", "z", "x")) else "st"
    ihr_suffix = "et" if singular.endswith(("d", "t")) else "t"
    return [singular, singular + du_suffix, singular, singular + "en", singular + ihr_suffix, singular + "en"]


def parse_notes(notes: str) -> tuple[str | None, str | None, str | None, tuple[str, ...] | None]:
    notes = normalize_spelling(notes)
    match = re.search(r"\(([^)]{3,120})\)", notes)
    if not match:
        return None, None, None, None
    inside = match.group(1)
    if inside.strip().startswith("+"):
        return None, None, None, None
    if not re.search(r"[a-zäöüß]{2,}", inside, re.I):
        return None, None, None, None
    inside = re.sub(r"\b(?:Vt|Vi|Vr|V)\b.*$", "", inside).strip()
    inside = inside.replace(",,", ",")
    aux: tuple[str, ...] | None = None

    if "ist/hat" in inside or "hat/ist" in inside:
        aux = ("sein", "haben")
        inside = inside.replace("ist/hat", "").replace("hat/ist", "")
    elif re.search(r"\bist\b", inside):
        aux = ("sein",)
        inside = re.sub(r"\bist\b", "", inside)
    elif re.search(r"\bhat\b", inside):
        aux = ("haben",)
        inside = re.sub(r"\bhat\b", "", inside)

    pieces = [p.strip(" ,;") for p in inside.split(",") if p.strip(" ,;")]
    third: str | None = None
    preterite: str | None = None
    participle: str | None = None

    if len(pieces) >= 3:
        third, preterite, participle = pieces[0], pieces[1], pieces[2]
    elif len(pieces) == 2:
        first, second = pieces
        if second.startswith(("ge", "be", "er", "ver", "zer", "ent", "emp")) or second.endswith(("en", "t")):
            preterite, participle = first, second
        else:
            third, preterite = first, second
    elif len(pieces) == 1:
        tokens = pieces[0].split()
        if len(tokens) >= 2:
            preterite, participle = tokens[0], tokens[1]

    def cleanup(value: str | None) -> str | None:
        if not value:
            return None
        value = re.sub(r"\s+", " ", value).strip()
        value = re.sub(r"^(?:hat|ist)\s+", "", value)
        value = value.split("/")[0] if "/" in value and not value.startswith("ge") else value
        value = value.replace(" ", "")
        return normalize_spelling(value)

    return cleanup(third), cleanup(preterite), cleanup(participle), aux


PRINCIPAL_OVERRIDES: dict[str, tuple[str | None, str, str, tuple[str, ...]]] = {
    "beraten": ("berät", "beriet", "beraten", ("haben",)),
    "bergen": ("birgt", "barg", "geborgen", ("haben",)),
    "berufen": (None, "berief", "berufen", ("haben",)),
    "brechen": ("bricht", "brach", "gebrochen", ("haben",)),
    "denken": (None, "dachte", "gedacht", ("haben",)),
    "empfangen": ("empfängt", "empfing", "empfangen", ("haben",)),
    "enthalten": ("enthält", "enthielt", "enthalten", ("haben",)),
    "fahren": ("fährt", "fuhr", "gefahren", ("sein", "haben")),
    "fangen": ("fängt", "fing", "gefangen", ("haben",)),
    "gebieten": (None, "gebot", "geboten", ("haben",)),
    "gleichen": (None, "glich", "geglichen", ("haben",)),
    "hinterlassen": ("hinterlässt", "hinterließ", "hinterlassen", ("haben",)),
    "kommen": (None, "kam", "gekommen", ("sein",)),
    "messen": ("misst", "maß", "gemessen", ("haben",)),
    "raten": ("rät", "riet", "geraten", ("haben",)),
    "rennen": (None, "rannte", "gerannt", ("sein",)),
    "schweigen": (None, "schwieg", "geschwiegen", ("haben",)),
    "sehen": ("sieht", "sah", "gesehen", ("haben",)),
    "sprechen": ("spricht", "sprach", "gesprochen", ("haben",)),
    "treiben": (None, "trieb", "getrieben", ("haben",)),
    "treten": ("tritt", "trat", "getreten", ("sein", "haben")),
    "übergeben": ("übergibt", "übergab", "übergeben", ("haben",)),
    "überlassen": ("überlässt", "überließ", "überlassen", ("haben",)),
    "übertragen": ("überträgt", "übertrug", "übertragen", ("haben",)),
    "verbinden": (None, "verband", "verbunden", ("haben",)),
    "vergeben": ("vergibt", "vergab", "vergeben", ("haben",)),
    "weisen": (None, "wies", "gewiesen", ("haben",)),
    "wachsen": ("wächst", "wuchs", "gewachsen", ("sein",)),
}


def parts_for(entry: dict[str, Any]) -> Parts:
    word = str(entry["german"]).lower()
    if word in MANUAL:
        return MANUAL[word]
    if word in PRINCIPAL_OVERRIDES:
        third, pret, part, aux = PRINCIPAL_OVERRIDES[word]
        return Parts(
            present_from_third(word, third),
            preterite_forms_from_singular(pret),
            part,
            aux,
            "manual principal-parts override",
        )

    third, pret, part, parsed_aux = parse_notes(str(entry.get("notes", "")))
    present = present_from_third(word, third)
    preterite = preterite_forms_from_singular(pret or weak_preterite_from_infinitive(word))
    partizip_ii = part or regular_participle(word)

    aux: tuple[str, ...]
    if parsed_aux:
        aux = parsed_aux
    elif word in SEIN_AUX_VERBS or str(entry.get("notes", "")).strip().startswith("Vi") and word in SEIN_AUX_VERBS:
        aux = ("sein",)
    else:
        aux = ("haben",)
    confidence = "vocab principal parts" if pret or part or third else "weak regular rule"
    return Parts(present, preterite, partizip_ii, aux, confidence)


def forms(values: list[str]) -> dict[str, str]:
    return dict(zip(PERSONS, values, strict=True))


def tense(group: str, label: str, values: list[str]) -> dict[str, Any]:
    return {"type": "person", "group_label": group, "tense_label": label, "forms": forms(values)}


def single(group: str, label: str, values: list[str]) -> dict[str, Any]:
    return {"type": "single", "group_label": group, "tense_label": label, "forms": values}


HABEN_PRESENT = ["habe", "hast", "hat", "haben", "habt", "haben"]
HABEN_PRET = ["hatte", "hattest", "hatte", "hatten", "hattet", "hatten"]
HABEN_KI = ["habe", "habest", "habe", "haben", "habet", "haben"]
SEIN_PRESENT = ["bin", "bist", "ist", "sind", "seid", "sind"]
SEIN_PRET = ["war", "warst", "war", "waren", "wart", "waren"]
SEIN_KI = ["sei", "seiest", "sei", "seien", "seiet", "seien"]
WERDEN_PRESENT = ["werde", "wirst", "wird", "werden", "werdet", "werden"]
WUERDE = ["würde", "würdest", "würde", "würden", "würdet", "würden"]


def aux_values(aux: tuple[str, ...], tense_name: str) -> list[str]:
    tables = {
        ("haben", "present"): HABEN_PRESENT,
        ("haben", "preterite"): HABEN_PRET,
        ("haben", "konjunktiv_i"): HABEN_KI,
        ("sein", "present"): SEIN_PRESENT,
        ("sein", "preterite"): SEIN_PRET,
        ("sein", "konjunktiv_i"): SEIN_KI,
    }
    selected = [tables[(a, tense_name)] for a in aux]
    if len(selected) == 1:
        return selected[0]
    return ["/".join(table[i] for table in selected) for i in range(6)]


def aux_infinitive(aux: tuple[str, ...]) -> str:
    return "/".join("sein" if a == "sein" else "haben" for a in aux)


def konjunktiv_i_present(infinitive: str) -> list[str]:
    if infinitive == "sein":
        return ["sei", "seiest", "sei", "seien", "seiet", "seien"]
    stem = infinitive_stem(infinitive)
    if infinitive.endswith("eln"):
        stem = infinitive[:-1]
        return [stem[:-2] + "le", stem + "est", stem[:-2] + "le", infinitive, stem + "et", infinitive]
    return [stem + "e", stem + "est", stem + "e", infinitive, stem + "et", infinitive]


def imperative_forms(infinitive: str, parts: Parts) -> list[str]:
    if infinitive == "sein":
        return ["None", "sei", "None", "seien wir", "seid", "seien Sie"]
    if infinitive == "haben":
        return ["None", "hab", "None", "haben wir", "habt", "haben Sie"]
    stem = infinitive_stem(infinitive)
    du = parts.present[1]
    if du.endswith("st"):
        du = du[:-2]
    elif du.endswith("t"):
        du = du[:-1]
    if needs_e(stem):
        du = stem + "e"
    return ["None", du, "None", f"{infinitive} wir", parts.present[4], f"{infinitive} Sie"]


def partizip_i_form(infinitive: str) -> str:
    specials = {
        "sein": "seiend",
        "tun": "tuend",
    }
    return specials.get(infinitive, infinitive + "d")


def build_tenses(infinitive: str, parts: Parts) -> dict[str, Any]:
    aux_present = aux_values(parts.aux, "present")
    aux_preterite = aux_values(parts.aux, "preterite")
    aux_ki = aux_values(parts.aux, "konjunktiv_i")
    part = parts.partizip_ii
    aux_inf = aux_infinitive(parts.aux)
    ki = konjunktiv_i_present(infinitive)
    part_i = partizip_i_form(infinitive)

    return {
        "indikativ_praesens": tense("Indikativ", "Präsens", parts.present),
        "indikativ_praeteritum": tense("Indikativ", "Präteritum", parts.preterite),
        "indikativ_perfekt": tense("Indikativ", "Perfekt", [f"{aux_present[i]} {part}" for i in range(6)]),
        "indikativ_plusquamperfekt": tense(
            "Indikativ", "Plusquamperfekt", [f"{aux_preterite[i]} {part}" for i in range(6)]
        ),
        "indikativ_futur_i": tense("Indikativ", "Futur I", [f"{WERDEN_PRESENT[i]} {infinitive}" for i in range(6)]),
        "indikativ_futur_ii": tense(
            "Indikativ", "Futur II", [f"{WERDEN_PRESENT[i]} {part} {aux_inf}" for i in range(6)]
        ),
        "konjunktiv_i": tense("Konjunktiv", "Konjunktiv I", ki),
        "konjunktiv_i_perfekt": tense(
            "Konjunktiv", "Konjunktiv I Perfekt", [f"{aux_ki[i]} {part}" for i in range(6)]
        ),
        "konjunktiv_ii": tense("Konjunktiv", "Konjunktiv II (würde-Form)", [f"{WUERDE[i]} {infinitive}" for i in range(6)]),
        "konjunktiv_ii_perfekt": tense(
            "Konjunktiv", "Konjunktiv II Perfekt (würde-Form)", [f"{WUERDE[i]} {part} {aux_inf}" for i in range(6)]
        ),
        "imperativ": single("Imperativ", "Imperativ", imperative_forms(infinitive, parts)),
        "partizip_i": single("Infinit", "Partizip I", [part_i]),
        "partizip_ii": single("Infinit", "Partizip II", [part]),
        "infinitiv": single("Infinit", "Infinitiv", [infinitive]),
        "zu_infinitiv": single("Infinit", "zu + Infinitiv", [f"zu {infinitive}"]),
    }


def select_entries(vocab: list[dict[str, Any]]) -> list[dict[str, Any]]:
    verb_lemmas = {str(e.get("german", "")).lower() for e in vocab if is_verb_entry(e)}
    by_word = {str(e.get("german", "")).lower(): e for e in vocab}
    seen: set[str] = set()
    candidates: list[dict[str, Any]] = []
    for word in MANDATORY:
        source = by_word.get(word) or {
            "german": word,
            "meaning": "",
            "chinese": "",
            "notes": "manual",
            "rank": 999999,
        }
        seen.add(word)
        candidates.append(source)
    for entry in vocab:
        word = str(entry.get("german", "")).lower()
        if word in seen or not is_verb_entry(entry):
            continue
        if looks_separable(word, verb_lemmas):
            continue
        try:
            parts_for(entry)
        except Exception:
            continue
        seen.add(word)
        candidates.append(entry)

    def sort_key(entry: dict[str, Any]) -> tuple[float, int, str]:
        word = str(entry["german"]).lower()
        return (-german_frequency(word, int(entry.get("rank") or 999999)), int(entry.get("rank") or 999999), word)

    selected = sorted(candidates, key=sort_key)[:TARGET_COUNT]
    if len(selected) < 250:
        raise RuntimeError(f"Only {len(selected)} high-confidence German verbs selected")
    return selected


def build() -> list[dict[str, Any]]:
    vocab = load_js_array(VOCAB_PATH, "GERMAN_VOCABULARY_DATA")
    selected = select_entries(vocab)
    entries: list[dict[str, Any]] = []
    for rank, entry in enumerate(selected, start=1):
        infinitive = str(entry["german"]).lower()
        parts = parts_for(entry)
        entries.append(
            {
                "rank": rank,
                "infinitive": infinitive,
                "frequency": german_frequency(infinitive, int(entry.get("rank") or 999999)),
                "english": clean_gloss(str(entry.get("meaning") or "")),
                "chinese": clean_gloss(str(entry.get("chinese") or entry.get("meaning") or "")),
                "tenses": build_tenses(infinitive, parts),
            }
        )
    return entries


def main() -> None:
    data = build()
    header = (
        "// Auto-generated by scripts/build_german_conjugations.py\n"
        f"// Source: data/german-vocabulary.js notes + wordfreq Zipf frequency; total entries: {len(data)}; "
        "schema mirrors data/conjugations-all-tenses.js; separable-prefix verbs are filtered unless explicit\n"
    )
    OUT_PATH.write_text(
        header
        + "const GERMAN_CONJUGATION_DATA = "
        + json.dumps(data, ensure_ascii=False, indent=2)
        + ";\n",
        encoding="utf-8",
    )
    print(f"Wrote {len(data)} entries to {OUT_PATH}")


if __name__ == "__main__":
    main()
