"""Shared writer for grammar/1 data files (docs/data-schema.md).

Every grammar book is emitted through `canonicalize()` + `write()`:

  * slugs are ASCII and positional: part `p<N>`, chapter `p<N>/ch<NN>`,
    topic `p<N>/ch<NN>/t<NN>` (1-based, in reading order);
  * every slug the topic had before is kept in `meta.aliases` (old -> new),
    composed with any aliases already in the file, so saved positions,
    deep links and course references keep resolving;
  * intra-content links that point at an old slug are rewritten;
  * every topic has a CEFR `level`; `meta.levels` and `meta.topicCount`
    are derived from the tree.

`canonicalize()` is idempotent: running it on its own output changes nothing.

Run `python3 scripts/canonicalize_grammar.py [it de en fr]` to re-canonicalize
the shipped files in place (the Italian and German files are their own source
of truth; English and French are regenerated by their builders, which call
this module).
"""

import json
import os
import re
import subprocess

from data_module import register_footer

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

CEFR = ['A1', 'A2', 'B1', 'B2', 'C1', 'C2']
SLUG_RE = re.compile(r'^p\d+/ch\d{2}/t\d{2}$')

# Per-language file facts.  `builder` is what regenerates the file.
LANGS = {
    'it': {
        'file': 'data/it-grammar.js',
        'global': 'GRAMMAR_DATA',
        'builder': 'scripts/canonicalize_grammar.py',
        'sources': ['意大利语语法书 Markdown 转换稿（原始书稿与 grammar_tree.json 已于 2026-09-30 删除）'],
        'licences': ['未声明：原书稿已删除，本文件为冻结产物，只能就地修改'],
        'header': [
            '// data/it-grammar.js — 意大利语语法书（grammar/1，docs/data-schema.md）',
            '// FROZEN ARTEFACT — the source books were deleted on 2026-09-30, so this file',
            '// is its own source of truth.  Edit it in place, then normalise it with',
            '//   python3 scripts/canonicalize_grammar.py it',
            '// Topic levels are a title-based heuristic (meta.levelSource = "heuristic"),',
            '// see ITALIAN_LEVEL_RULES in scripts/canonicalize_grammar.py.',
        ],
    },
    'de': {
        'file': 'data/de-grammar.js',
        'global': 'GERMAN_GRAMMAR_DATA',
        'builder': 'scripts/canonicalize_grammar.py',
        'sources': [
            'deutsch-data/grammar/docs Docusaurus 语料（无许可证，已于 2026-09-30 删除；转换稿保留在本文件）',
            'Dimenticato 原创专题（原由 scripts/build_german_grammar.py 生成）',
        ],
        'licences': ['原创专题：为 Dimenticato 撰写', '旧语料：未声明许可证'],
        'header': [
            '// data/de-grammar.js — 德语语法书（grammar/1，docs/data-schema.md）',
            '// SOURCE OF TRUTH — the Docusaurus corpus scripts/build_german_grammar.py read',
            '// (deutsch-data/grammar/docs) is gone, so this file is edited directly.',
            '// After editing, normalise it with:  python3 scripts/canonicalize_grammar.py de',
            '// Validate with:                     node scripts/validate_german_grammar.js',
        ],
    },
    'en': {
        'file': 'data/en-grammar.js',
        'global': 'ENGLISH_GRAMMAR_DATA',
        'builder': 'scripts/build_english_grammar.py',
        'sources': ['scripts/english_grammar_src/*.md（原创）'],
        'licences': ['原创文本，为 Dimenticato 撰写'],
        'header': None,  # supplied by the builder
    },
    'fr': {
        'file': 'data/fr-grammar.js',
        'global': 'FRENCH_GRAMMAR_DATA',
        'builder': 'scripts/build_french_grammar.py',
        'sources': [
            'scripts/build_french_grammar.py 内原创内容',
            'data/fr-conjugations.js（变位表交叉核对：Wiktionary via kaikki.org；Lexique 3.83）',
        ],
        'licences': ['原创文本，为 Dimenticato 撰写', '变位核对数据：CC BY-SA 4.0 + GFDL；Lexique CC BY-SA 4.0'],
        'header': None,
    },
}


def read(code, path=None):
    """Load a grammar data file through Node (it is a classic script)."""
    path = path or os.path.join(ROOT, LANGS[code]['file'])
    script = (
        "const vm=require('vm'),fs=require('fs');"
        "const ctx={module:undefined};ctx.globalThis=ctx;vm.createContext(ctx);"
        "vm.runInContext(fs.readFileSync(process.argv[1],'utf8'),ctx);"
        "process.stdout.write(JSON.stringify(ctx.DIM_DATA.grammar[process.argv[2]]));"
    )
    out = subprocess.check_output(['node', '-e', script, path, code])
    return json.loads(out.decode('utf-8'))


LINK_RE = re.compile(r'(\]\(\s*<?)([^)\s>]+)(>?(?:\s+"[^"]*")?\s*\))')
HREF_RE = re.compile(r'(href=")([^"]+)(")')
ROUTE_PREFIX_RE = re.compile(r'^(#?/?(?:[a-z]{2}/)?grammar/book/|#)')


def _rewrite_links(md, aliases, known):
    """Point links at old slugs (`](old)`, `href="old"`, `#/xx/grammar/book/old`) at the new one."""
    def fix(target):
        prefix = ''
        bare = target
        m = ROUTE_PREFIX_RE.match(target)
        if m:
            prefix, bare = m.group(1), target[m.end():]
        if bare in aliases and bare not in known:
            return prefix + aliases[bare]
        return target

    md = LINK_RE.sub(lambda m: m.group(1) + fix(m.group(2)) + m.group(3), md)
    md = HREF_RE.sub(lambda m: m.group(1) + fix(m.group(2)) + m.group(3), md)
    return md


def canonicalize(data, code, level_for=None, level_source=None, extra_meta=None):
    """Return grammar/1 data for `data` ({meta?, tree, content}).

    level_for(topic, part, chapter) supplies a level for topics without one.
    """
    old_meta = dict(data.get('meta') or {})
    old_aliases = dict(old_meta.get('aliases') or {})
    content_in = data['content']

    mapping = {}
    parts = []
    used_levels = set()
    for pi, part in enumerate(data['tree']['parts'], 1):
        pslug = 'p%d' % pi
        chapters = []
        for ci, chapter in enumerate(part.get('chapters') or [], 1):
            cslug = '%s/ch%02d' % (pslug, ci)
            topics = []
            for ti, topic in enumerate(chapter.get('topics') or [], 1):
                tslug = '%s/t%02d' % (cslug, ti)
                old = topic['slug']
                if old in mapping:
                    raise SystemExit('grammar_schema(%s): duplicate topic slug %r' % (code, old))
                if old not in content_in:
                    raise SystemExit('grammar_schema(%s): topic %r has no content' % (code, old))
                mapping[old] = tslug
                level = topic.get('level')
                if level not in CEFR and level_for:
                    level = level_for(topic, part, chapter)
                if level not in CEFR:
                    raise SystemExit('grammar_schema(%s): topic %r has no CEFR level' % (code, old))
                used_levels.add(level)
                topics.append({'title': topic['title'], 'slug': tslug, 'level': level})
            chapters.append({'title': chapter['title'], 'slug': cslug, 'topics': topics})
        parts.append({'title': part['title'], 'slug': pslug, 'chapters': chapters})

    orphans = sorted(set(content_in) - set(mapping))
    if orphans:
        raise SystemExit('grammar_schema(%s): content keys not in tree: %s' % (code, orphans[:5]))

    known = set(mapping.values())
    aliases = {}
    # earlier generations first (old -> mid -> new), then this generation
    for old, mid in old_aliases.items():
        target = mapping.get(mid, mid)
        if old != target and old not in known:
            aliases[old] = target
    for old, new in mapping.items():
        if old != new:
            aliases[old] = new
    dangling = sorted(a for a, t in aliases.items() if t not in known)
    if dangling:
        raise SystemExit('grammar_schema(%s): aliases point at missing topics: %s' % (code, dangling[:5]))

    content = {}
    for old, new in mapping.items():
        content[new] = _rewrite_links(content_in[old], aliases, known)

    facts = LANGS[code]
    meta = {
        'schema': 'grammar/1',
        'lang': code,
        'name': old_meta.get('name') or old_meta.get('title') or '',
        'title': old_meta.get('title') or '',
        'description': old_meta.get('description') or '',
        'count': len(mapping),
        'topicCount': len(mapping),
        'levels': [lv for lv in CEFR if lv in used_levels],
    }
    if level_source or old_meta.get('levelSource'):
        meta['levelSource'] = level_source or old_meta.get('levelSource')
    meta['builder'] = facts['builder']
    meta['sources'] = facts['sources']
    meta['licences'] = facts['licences']
    if extra_meta:
        meta.update(extra_meta)
    meta['aliases'] = dict(sorted(aliases.items(), key=lambda kv: (kv[1], kv[0])))
    return {'meta': meta, 'tree': {'parts': parts}, 'content': content}


def render(code, data, header=None):
    name = LANGS[code]['global']
    header = header if header is not None else LANGS[code]['header']
    meta = data['meta']
    aliases = meta['aliases']
    meta_wo = {k: v for k, v in meta.items() if k != 'aliases'}
    lines = list(header or [])
    lines.append('')
    lines.append('const %s = {' % name)
    meta_json = json.dumps(meta_wo, ensure_ascii=False)
    lines.append('"meta": ' + meta_json[:-1] + ', "aliases": {')
    items = list(aliases.items())
    for i, (old, new) in enumerate(items):
        lines.append('  %s: %s%s' % (json.dumps(old, ensure_ascii=False), json.dumps(new),
                                     ',' if i < len(items) - 1 else ''))
    lines.append('}},')
    lines.append('"tree": %s,' % json.dumps(data['tree'], ensure_ascii=False, indent=1))
    lines.append('"content": {')
    keys = list(data['content'].keys())
    for i, slug in enumerate(keys):
        lines.append('%s: %s%s' % (json.dumps(slug), json.dumps(data['content'][slug], ensure_ascii=False),
                                   ',' if i < len(keys) - 1 else ''))
    lines.append('}};')
    lines.append('')
    lines.append("if (typeof module !== 'undefined' && module.exports) {")
    lines.append('  module.exports = %s;' % name)
    lines.append('}')
    lines.append(register_footer('grammar', code, name))
    return '\n'.join(lines)


def write(code, data, header=None, path=None):
    path = path or os.path.join(ROOT, LANGS[code]['file'])
    text = render(code, data, header)
    with open(path, 'w', encoding='utf-8', newline='\n') as fh:
        fh.write(text)
    return path
